name: Playwright Tests and Report Deployment

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests with retry on failure
        run: |
          set +e
          echo "▶️ Running full test suite..."
          npx playwright test --reporter=html
          exit_code=$?

          if [ $exit_code -ne 0 ]; then
            echo "❌ Initial test run failed. Re-running failed tests..."
            npx playwright test --last-failed --reporter=html
            exit_code=$?
          fi

          exit $exit_code
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        continue-on-error: true  # Let the workflow continue to deploy the report

      - name: Upload Playwright report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy: # Deploy Playwright Report URL: https://<your-github-username>.github.io/<repo-name>/
    name: Deploy Playwright Report to GitHub Pages
    if: always()  # Always run even if tests fail
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Download Playwright report artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: ./playwright-report

      - name: Add .nojekyll to allow asset folders like _trace or _assets
        run: touch ./playwright-report/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages
