name: Playwright Tests and Report Deployment

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

# Define permissions for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Set up Node.js with a specific LTS version
      - uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify exact LTS version for consistency

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test
        env:
          PASSWORD: ${{ secrets.PASSWORD }}  # Ensure PASSWORD is set in repo secrets

      # Upload Playwright report as artifact (always, even on failure)
      - name: Upload Playwright report as artifact
        if: always()  # Ensures it runs even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  deploy:
    # Only run deployment on main/master push and if tests succeed
    needs: test
    if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && success()
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Download the artifact
      - name: Download Playwright report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      # Setup Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Upload artifact to Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './playwright-report'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4